apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend-svc  # Уникальное имя с учетом релиза
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}
  selector:
    app: {{ .Chart.Name }}-backend